### ISSUE TITLE
Wrong openh version & entrypoint.sh permissions

### ISSUE THREAD

**Issue by stmn** [renoki-co/browser-streamer#1]
Hello,

currently it is impossible to run because of two things:

1. There is completely different versions of openh package:

in Dockerfile:
```
curl -s http://ciscobinary.openh264.org/libopenh264-2.1.1-linux64.6.so.bz2 -o /tmp/libopenh264-2.1.1-linux64.6.so.bz2 && \
    chmod a+r /tmp/libopenh264-2.1.1-linux64.6.so.bz2 && \
```

in firefox.sh:
```
mkdir -p /tmp/firefox-profile/gmp-gmpopenh264/1.8.1.1/
unzip /openh264-1.8.1.1.zip -d /tmp/firefox-profile/gmp-gmpopenh264/1.8.1.1/
```

2. Also I think you should fix file permissions for entrypoint.sh file in quay.io/renokico/browser-streamer:1.0 image because there is permission error when using it.

**Comment by rennokki** [comment]
Sorry for the delay. I had other priorities. This project was made to help me with another project that got postponed. :)
